services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '3080:3080'
    volumes:
      - ./output:/app/output
    environment:
      RUST_ENV: production
