services:
  - name: frontend
    type: web
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /

  - name: backend
    type: web
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: RUST_ENV
        value: production
    healthCheckPath: /health

  - name: nginx
    type: web
    runtime: docker
    dockerfilePath: ./nginx.Dockerfile
    healthCheckPath: /
