services:
  - name: frontend
    type: web
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /

  - name: backend
    type: web
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: RUST_ENV
        value: production
      - key: DATABASE_URL
        value: postgres://postgres:postgres@postgres:5432/postgres
    healthCheckPath: /health

  - name: nginx
    type: web
    runtime: docker
    dockerfilePath: ./nginx.Dockerfile
    healthCheckPath: /

  - name: postgres
    type: database
    databaseType: postgres
    plan: free
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: postgres
      - key: POSTGRES_DB
        value: postgres

